import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";

export const Route = createFileRoute("/auth")({ component: AuthPage });
function AuthPage() { const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [signup, setSignup] = useState(false); const submit = async () => { setMessage(""); const result = signup ? await supabase.auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/admin` } }) : await supabase.auth.signInWithPassword({ email, password }); if (result.error) setMessage(result.error.message); else if (signup) setMessage("Check your email to confirm your account."); else navigate({ to: "/admin" }); };
  return <div className="mx-auto max-w-md px-4 py-16"><p className="text-sm font-black uppercase tracking-[.3em] text-primary">Store management</p><h1 className="font-display mt-2 text-4xl font-black uppercase">Admin sign in</h1><div className="mt-8 space-y-4"><Input type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} maxLength={255}/><Input type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={8} maxLength={72}/><Button className="h-12 w-full rounded-none" onClick={submit}>{signup ? "Create account" : "Sign in"}</Button><Button variant="outline" className="h-12 w-full rounded-none" onClick={async () => { const result = await lovable.auth.signInWithOAuth("google", { redirect_uri: `${window.location.origin}/admin` }); if (result.error) setMessage(String(result.error)); }}>Continue with Google</Button><Button variant="link" className="w-full" onClick={() => setSignup(!signup)}>{signup ? "Already have an account? Sign in" : "Create an account"}</Button><Button variant="link" className="w-full" onClick={async () => { if (!email) { setMessage("Enter your email first."); return; } const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); setMessage(error ? error.message : "Password reset email sent."); }}>Forgot password?</Button>{message && <p className="text-center text-sm text-muted-foreground">{message}</p>}</div></div>; }