import { createFileRoute, Link } from "@tanstack/react-router";
import { Minus, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useCart } from "@/components/cart-context";
import { money } from "@/lib/products";

export const Route = createFileRoute("/cart")({ head: () => ({ meta: [{ title: "Your Cart — Den Mond" }, { name: "description", content: "Review your Den Mond order and send it via WhatsApp." }] }), component: CartPage });
function CartPage() { const cart = useCart(); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [method, setMethod] = useState("Delivery"); const [notes, setNotes] = useState(""); const total = cart.items.reduce((sum, item) => sum + (item.product.price ?? 0) * item.quantity, 0);
  const checkout = () => { if (!name.trim() || !phone.trim()) return; const lines = cart.items.map((item) => `• ${item.product.name} — ${item.color}, ${item.size} × ${item.quantity} (${money((item.product.price ?? 0) * item.quantity)})`); const message = [`Hello Den Mond! I would like to place an order:`, "", ...lines, "", `Total: ${money(total)}`, `Name: ${name.trim()}`, `Phone: ${phone.trim()}`, `Fulfilment: ${method}`, notes.trim() ? `Address / notes: ${notes.trim()}` : ""].filter(Boolean).join("\n"); window.open(`https://wa.me/27798349810?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); };
  if (!cart.items.length) return <div className="mx-auto max-w-xl px-4 py-24 text-center"><h1 className="font-display text-5xl font-black uppercase">Your cart is empty</h1><Button asChild className="mt-7 rounded-none"><Link to="/shop">Shop the collection</Link></Button></div>;
  return <div className="mx-auto grid max-w-7xl gap-12 px-4 py-12 sm:px-6 lg:grid-cols-[1.2fr_.8fr]"><div><h1 className="font-display text-5xl font-black uppercase">Your cart</h1><div className="mt-8 divide-y divide-border border-y border-border">{cart.items.map((item, index) => <div key={`${item.product.id}-${item.color}-${item.size}`} className="grid grid-cols-[96px_1fr] gap-4 py-5"><img src={item.product.images[0]} alt={item.product.name} className="aspect-[4/5] w-full bg-muted object-cover"/><div><div className="flex justify-between gap-4"><div><h2 className="font-display text-lg font-black uppercase">{item.product.name}</h2><p className="text-sm text-muted-foreground">{item.color} / {item.size}</p></div><Button variant="ghost" size="icon" onClick={() => cart.remove(index)} aria-label="Remove item"><Trash2/></Button></div><div className="mt-4 flex items-center justify-between"><div className="flex items-center border"><Button variant="ghost" size="icon" onClick={() => cart.setQuantity(index, item.quantity - 1)}><Minus/></Button><span>{item.quantity}</span><Button variant="ghost" size="icon" onClick={() => cart.setQuantity(index, item.quantity + 1)}><Plus/></Button></div><strong>{money((item.product.price ?? 0) * item.quantity)}</strong></div></div></div>)}</div></div><aside className="bg-foreground p-6 text-background sm:p-8"><h2 className="font-display text-3xl font-black uppercase">Order details</h2><div className="mt-6 space-y-4"><Input className="h-12 bg-background text-foreground" placeholder="Full name *" maxLength={100} value={name} onChange={(e) => setName(e.target.value)}/><Input className="h-12 bg-background text-foreground" placeholder="Phone number *" maxLength={25} value={phone} onChange={(e) => setPhone(e.target.value)}/><div className="grid grid-cols-2 gap-2">{["Delivery","Pickup"].map((value) => <Button key={value} variant={method === value ? "default" : "outline"} onClick={() => setMethod(value)} className="rounded-none border-background/40">{value}</Button>)}</div><Textarea className="min-h-28 bg-background text-foreground" placeholder="Delivery address or order notes" maxLength={500} value={notes} onChange={(e) => setNotes(e.target.value)}/></div><div className="mt-7 flex justify-between border-t border-background/20 pt-5 text-xl"><span>Total</span><strong>{money(total)}</strong></div><Button className="mt-6 h-13 w-full rounded-none font-black uppercase" disabled={!name.trim() || !phone.trim()} onClick={checkout}>Checkout on WhatsApp</Button><p className="mt-3 text-xs text-background/60">WhatsApp will open with your order ready to send. Payment and delivery are confirmed directly with Den Mond.</p></aside></div>; }