import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Check, Minus, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { listProducts } from "@/lib/products.functions";
import { money } from "@/lib/products";
import { useCart } from "@/components/cart-context";
export const Route = createFileRoute("/product/$slug")({ component: ProductPage });
function ProductPage() { const { slug } = Route.useParams(); const { data = [], isLoading } = useQuery({ queryKey: ["products"], queryFn: () => listProducts() }); const product = data.find((p) => p.slug === slug); const [image, setImage] = useState(0); const [color, setColor] = useState(""); const [size, setSize] = useState(""); const [quantity, setQuantity] = useState(1); const [added, setAdded] = useState(false); const cart = useCart(); if (isLoading) return <div className="p-12">Loading…</div>; if (!product) return <div className="mx-auto max-w-xl px-4 py-24 text-center"><h1 className="font-display text-4xl uppercase">Product not found</h1><Button asChild className="mt-6"><Link to="/shop">Back to shop</Link></Button></div>; const selectedColor = color || product.colors[0] || "Standard"; const selectedSize = size || product.sizes[0] || "One size"; return <div className="mx-auto grid max-w-7xl gap-10 px-4 py-8 sm:px-6 lg:grid-cols-[1.25fr_.75fr] lg:py-14"><div><div className="bg-muted"><img src={product.images[image]} alt={`${product.name} view ${image + 1}`} className="aspect-[4/5] w-full object-contain"/></div>{product.images.length > 1 && <div className="mt-3 grid grid-cols-5 gap-2">{product.images.map((url, i) => <button key={url} onClick={() => setImage(i)} className={`bg-muted ${i === image ? "ring-2 ring-primary" : ""}`}><img src={url} alt="" className="aspect-square w-full object-cover"/></button>)}</div>}</div><div className="lg:sticky lg:top-28 lg:self-start"><p className="text-xs font-black uppercase tracking-[.25em] text-primary">{product.category}</p><h1 className="font-display mt-2 text-4xl font-black uppercase sm:text-5xl">{product.name}</h1><p className="mt-4 text-xl font-black">{money(product.price)}</p><p className="mt-6 leading-7 text-muted-foreground">{product.description}</p><Option label="Colour" values={product.colors} selected={selectedColor} setSelected={setColor}/><Option label="Size" values={product.sizes} selected={selectedSize} setSelected={setSize}/><div className="mt-7 flex items-center gap-3"><div className="flex h-12 items-center border border-input"><Button variant="ghost" size="icon" onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus/></Button><span className="w-8 text-center font-bold">{quantity}</span><Button variant="ghost" size="icon" onClick={() => setQuantity(quantity + 1)}><Plus/></Button></div><Button className="h-12 flex-1 rounded-none font-black uppercase" disabled={product.price == null || !product.in_stock} onClick={() => { cart.add({ product, color: selectedColor, size: selectedSize, quantity }); setAdded(true); }}>{added ? <><Check/> Added</> : product.price == null ? "Awaiting price" : "Add to cart"}</Button></div></div></div>; }
function Option({ label, values, selected, setSelected }: { label: string; values: string[]; selected: string; setSelected: (v: string) => void }) { if (!values.length) return null; return <div className="mt-7"><p className="mb-3 text-xs font-black uppercase tracking-[.2em]">{label}: {selected}</p><div className="flex flex-wrap gap-2">{values.map((value) => <Button key={value} variant={value === selected ? "default" : "outline"} onClick={() => setSelected(value)} className="rounded-none">{value}</Button>)}</div></div>; }